services:
    backend:
        image: node:21.6-alpine3.18
        build:
            context: backend
        environment:
            NODE_DEV_SECRET: 469a5af35bb1956685ac2b96681b0a29e84f24a6199b51250a5ac7e4f706ddcb
            NODE_DEV_SALT: JDJiJDEwJHgvWXdtN2lEcGZzY2ZkUERucTFoME8=
            NODE_ENV: development
        ports:
            - "9000:9000"
        command: sh -c "npm install; ls; pwd; npm run dev;"
        volumes:
            - ".:/app"
        working_dir: /app/backend
    frontend:
        image: node:21.6-alpine3.18
        build:
            context: frontend
        environment:
            NODE_ENV: development
            VITE_API_BASE_URL: http://backend:9000
        command: sh -c "npm install; npm run dev -- --host;"
        volumes:
            - ".:/app"
        working_dir: /app/frontend
        ports:
            - "5173:5173"
    nginx:
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - ./backend/assets/:/usr/share/nginx/html
        restart: always
